env_file: ../.env

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/Sao_Paulo
    volumes:
      - ${DATA_DIR}/raddar:/config
      - ${DATA_DIR}/deluge/downloads:/downloads #optional
      - ${DATA_DIR}/multimedia/movies:/movies #optional
      - ${DATA_DIR}/multimedia/series:/series #optional
      - ${DATA_DIR}/multimedia/manga:/manga #optional
      - ${DATA_DIR}/multimedia/books:/books #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - io.portainer.accesscontrol.public