env_file: ../.env

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ${DATA_DIR}/sonnar/config:/config
      - ${DATA_DIR}/multimedia/series:/series #optional
      - ${DATA_DIR}/multimedia/movies:/movies #optional
      - ${DATA_DIR}/multimedia/books:/books #optional
      - ${DATA_DIR}/multimedia/movies:/manga #optional
      - ${DATA_DIR}/deluge/downloads:/downloads #optional
    ports:
      - 8765:8989
    restart: unless-stopped
    labels:
      - io.portainer.accesscontrol.public
