env_file: ../.env

services:
  xyops01:
    image: ghcr.io/pixlcore/xyops:latest
    container_name: xyops01
    hostname: xyops01

    init: true
    restart: unless-stopped

    environment:
      XYOPS_xysat_local: "true"
      TZ: America/Sao_Paulo

    volumes:
      - ${DATA_DIR}/xyops:/opt/xyops/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}:/mnt/data:ro
      - ${BACKUPS_DIR}:/mnt/backups
      - ../../scripts/routines:/mnt/scripts:ro

    ports:
      - "5522:5522"
      - "5523:5523"
    labels:
      - io.portainer.accesscontrol.public

